# Generated by Django 2.1.1 on 2019-08-21 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='tname',
            field=models.CharField(default=None, max_length=16, verbose_name='真实姓名'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='name',
            field=models.CharField(max_length=32, verbose_name='用户名'),
        ),
    ]
