# Generated by Django 2.1.1 on 2019-08-22 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_auto_20190821_0819'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classlist',
            name='teachers',
        ),
        migrations.RemoveField(
            model_name='classlist',
            name='tutor',
        ),
    ]
