# Generated by Django 2.1.1 on 2019-08-22 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_auto_20190822_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='classlist',
            name='teachers',
            field=models.ManyToManyField(limit_choices_to={'depart_id__in': [7, 8, 9]}, related_name='teach_classes', to='crm.UserInfo', verbose_name='任课老师'),
        ),
        migrations.AddField(
            model_name='classlist',
            name='tutor',
            field=models.ForeignKey(blank=True, limit_choices_to={'depart_id': 1}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes', to='crm.UserInfo', verbose_name='班主任'),
        ),
    ]
