# Generated by Django 2.1.1 on 2019-08-13 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app02', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='area',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='地址'),
        ),
        migrations.AddField(
            model_name='user',
            name='telephone',
            field=models.IntegerField(blank=True, null=True, verbose_name='移动电话'),
        ),
    ]
