# Generated by Django 2.1.1 on 2019-08-13 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app02', '0002_auto_20190813_0654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='telephone',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='移动电话'),
        ),
    ]
