# Generated by Django 2.1.1 on 2019-08-15 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app02', '0004_auto_20190815_0822'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='level',
            field=models.IntegerField(choices=[(1, '高级'), (2, '中级'), (3, '低级')], default=2, verbose_name='等级'),
        ),
    ]
